version: '3.4'

services:
  # nodejs from docker file [app1/Dockerfile]
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:3001
    volumes:
      - ./app1:/app
    networks:
      - app-network

  # nodejs from docker file [app2/Dockerfile]
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: app2
    restart: always
    ports:
      - 5002:3002
    volumes:
      - ./app2:/app
    networks:
      - app-network

  # nginx from docker file [./nginx/Dockerfile]
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - app1
      - app2
    ports:
      - 5000:80
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge